export const colors = {
  primary: "#185FA5",
  secondary: "#185FA5",
  accent: "#185FA5",
  lightBackground: "#E6F1FB",
  surface: "#F8F9FB",
  card: "#FFFFFF",
  border: "#D9E5F2",
  textPrimary: "#1A1A1A",
  textSecondary: "#6B7280",
  inputBackground: "#FFFFFF",
  inputPlaceholder: "#94A3B8",
  success: "#3B6D11",
  successLight: "#EAF3DE",
  warning: "#BA7517",
  warningLight: "#FAEEDA",
  error: "#A32D2D",
  errorLight: "#FCEBEB",
  errorBorder: "#F6CBCB",
  errorDark: "#A32D2D",
  errorVeryDark: "#7C1F1F",
  white: "#FFFFFF",
  black: "#111827",
};
